apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-Role
  namespace: jenkins
rules:
- apiGroups: [""]
  resource: ["pods", "pods/log", "pods/exec"]
  verbs: ["create", "get", "list", "watch", "delete"]


apiVersion: rbac.authorization.k8s.io/v1
kind: ROleBinding
metadata:
  name: jenkins-binding 
  namespace: jenkins
subjects: 
- kind: ServiceAccount
  name: jenkins
roleref:
  kind: Role
  name: jenkins-role 
  apiGroup: rbac.authorization.k8s.io